### ISSUE TITLE
excessive code in linear_regressor.py

### ISSUE THREAD

**Issue by charlieweinberger** [snowthesprite/machine-learning#10]
I noticed that you had a bit of code that seems unnecessary to me. On line 7, you have `self.funct = lambda a : a`. What is this supposed to do? As far as I can tell, this just returns the number that is inputted.

**Comment by snowthesprite** [comment]
Yes it does! The `self.funct = lambda a : a` is so that I can have as little as possible in my Logistic regressor. In the predict function, it returns `self.funct(y)`, so for the Linear regressor it just returns y, but for the Logistic it returns the `self.upper_bound/1+math.exp(y)`
