### ISSUE TITLE
Printing empty lines

### ISSUE THREAD

**Issue by RavenHex1296** [snowthesprite/machine-learning#11]
I notice that generally, for your tests (especially for the regressors) that you like to print empty lines using print(). Although it is fine, you could save quite a few lines by doing print(regressor.coefficients, "\n")   print(regressor.predict, "\n" .... etc. It essentially just prints an empty line after the coefficients or predict. Of course, this is purely optional, it just helps you get rid of a few lines.

**Comment by snowthesprite** [comment]
well dam, didn't know it did that. Thanks!! It will fix up some lines!
