### ISSUE TITLE
self.funct in linear_regressor.py

### ISSUE THREAD

**Issue by charlieweinberger** [snowthesprite/machine-learning#14]
In your linear_regressor.py code, you have a lambda function as an attribute of your LinearRegressor() class that reads `self.funct = lambda a : a`. Why do you have this? It seems to only take an input and return that same input. You only use it once, at the very end of your code. You have `self.funct(y)`. Unless there is a purpose for this lambda function that I do not see, I suggest that you get rid of the attribute and just have `return y` at the end.

**Comment by snowthesprite** [comment]
Its so I can hav the logistic regressor as a child class and not have to redo the predict function at the end. I'm not going to get rid of it.
